apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-e10g
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hsxp-tenant/rhtap-demo-app/hacbs-test-project-e10g@sha256:d91b5ae421a85da39676a573eb681be95cdcd15a52adb484453e8462200ad7d8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
