apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-e10g
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hsxp-tenant/rhtap-demo-app/hacbs-test-project-e10g@sha256:8d21f2b51a495fdf56a731d0fb8f6f04646b3d0d945b4e0a2c738bf20a9efdab
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
