apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-e10g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-e10g
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-e10g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-e10g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-e10g
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hsxp-tenant/rhtap-demo-app/hacbs-test-project-e10g@sha256:d91b5ae421a85da39676a573eb681be95cdcd15a52adb484453e8462200ad7d8
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
